# Generated by Django 3.1.1 on 2021-05-27 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='lowresolution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('low_resolution_Img', models.ImageField(upload_to='images/lowresolution/')),
            ],
        ),
    ]
