# Generated by Django 3.1.1 on 2021-06-12 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagetools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='originalresolution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orignial_resolution_Img', models.ImageField(upload_to='images/originalresolution/')),
            ],
        ),
        migrations.CreateModel(
            name='superresolution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('super_resolution_Img', models.ImageField(upload_to='images/superresolution')),
            ],
        ),
    ]
