# Generated by Django 3.1.1 on 2021-06-13 15:18

from django.db import migrations, models
import imagetools.storage


class Migration(migrations.Migration):

    dependencies = [
        ('imagetools', '0003_auto_20210612_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='originalresolution',
            name='original_resolution_Img',
            field=models.ImageField(storage=imagetools.storage.OverwriteStorage(), upload_to='images/originalresolution/'),
        ),
    ]
